name: Compile

on:
  push:
    paths:
      - '**.py'
      - 'drivers/**'
  schedule:
      - cron:  '0 0 */30 * *'
  release:
    types: [created]
  workflow_dispatch:
    branches:
    - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main

    - name: DIRECTORY STUFF
      run: |
        echo "Current directory: $(pwd)"
        echo "DIR Contents:"
        ls
        cat build/requirements.txt

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Run compile.py
      run: |
        pip install -r build/requirements.txt
        python build/compile.py

    - name: Set environment variables from file
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: |
        # Read the contents of the file into an array of lines
        LINES=($(cat variables.txt))
        # Loop over each line in the file
        for LINE in "${LINES[@]}"; do
          # Split each line into a name and a value
          NAME=$(echo "$LINE" | cut -d'=' -f1)
          VALUE=$(echo "$LINE" | cut -d'=' -f2)
          # Set the environment variable with the name and value
          echo "Setting environment variable '$NAME' to '$VALUE'"
          echo "::set-env name=$NAME::$VALUE"
        done
      # webdriverDL: ${{ env.webdriverDL }}
      # x64DL: ${{ env.x64DL }}
      # chromium: ${{ env.chromium }}
      # driver: ${{ env.driver }}
      # chromeVersion: ${{ env.chromeVersion }}

    - name: Move necessary files to compiled
      run: |
        cd $GITHUB_WORKSPACE
        mkdir compiled
        cp main.py requirements.txt compiled
        cp -r drivers compiled
        ls compiled

    - name: Download URLs
      run: |
        echo "webdriverDL: $webdriverDL"
        echo "x64DL: $x64DL"
        wget -O webdriver.zip $webdriverDL
        wget -O browser.zip $x64DL

    - name: Extract webdriver
      run: |
        unzip webdriver.zip -d compiled/drivers

    - name: Extract Browser
      run: |
        unzip browser.zip -d compiled/drivers
        mv compiled/drivers/ungoogled-chromium_${chromeVersion}_windows compiled/drivers/browser

    - name: Zip compiled directory
      run: |
        ls
        cd $GITHUB_WORKSPACE
        zip -r compiled-Win64.zip compiled/

    - name: Upload compiled artifact
      uses: actions/upload-artifact@v2
      with:
        name: compiled-Win64
        path: compiled/
        
    - name: Release Asset
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: compiled-Win64.zip
        body: " \n\nDownload compiled-Win64.zip for a quick setup. Just unzip and run main.py."
        append_body: true
        draft: false
        prerelease: false
      if: github.event_name == 'release'