name: Compile

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main

    - name: DIRECTORY STUFF
      run: |
        echo "Current directory: $(pwd)"
        echo "DIR Contents:"
        ls
        cat build/requirements.txt

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Run compile.py
      run: |
        pip install -r build/requirements.txt
        python build/compile.py

    - name: Set environment variables from file
      run: |
        # Read the contents of the file into an array of lines
        LINES=($(cat variables.txt))
        # Loop over each line in the file
        for LINE in "${LINES[@]}"; do
          # Split each line into a name and a value
          NAME=$(echo "$LINE" | cut -d'=' -f1)
          VALUE=$(echo "$LINE" | cut -d'=' -f2)
          # Set the environment variable with the name and value
          echo "Setting environment variable '$NAME' to '$VALUE'"
          echo "::set-env name=$NAME::$VALUE"
        done
      # webdriverDL: ${{ env.webdriverDL }}
      # x64DL: ${{ env.x64DL }}
      # chromium: ${{ env.chromium }}
      # driver: ${{ env.driver }}
      # chromeVersion: ${{ env.chromeVersion }}

    - name: Move necessary files to compiled
      run: |
        cd $GITHUB_WORKSPACE
        mkdir compiled
        cp main.py requirements.txt compiled
        cp -r drivers compiled

    - name: Download URLs
      run: |
        echo "webdriverDL: $webdriverDL"
        echo "x64DL: $x64DL"
        wget wget --progress=bar $webdriverDL
        wget wget --progress=bar $x64DL

    - name: Extract webdriver
      run: |
        unzip $x64DL -d compiled/drivers
    - name: Extract Browser
      run: |
        unzip $webdriverDL -d compiled/drivers
        mv compiled/drivers/ungoogled-chromium_$chromeVersion_windows compiled/drivers/browser

    - name: Zip compiled directory
      run: |
        cd $GITHUB_WORKSPACE
        zip -r compiled.zip compiled

    - name: Upload compiled artifact
      uses: actions/upload-artifact@v2
      with:
        name: compiled
        path: compiled.zip